name: Bash script workflow
on: ['push']
jobs:
    bash-script-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3 #ensures that your workflow has access to your repository's 
              #contents so that it can run scripts, aceess files or execute commands without actions/checkout@v3
              #your workflow wouldn't find bash_script_dit or any other files in your repo.
            - name: Grant execute permission to script
              run: chmod +x ./bash_script_dir/script.sh
              
            - name: Run a script
              run: ./bash_script_dir/script.sh
              #run: bash bash_script_dir/script.sh #to run this line remove grant steps