name: Dependent jobs
on:
    push:
        branches:
            - main

jobs:
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: steps in job 2
              run: echo "Hello in job2"
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: steps in job1
              run: echo "Hello in job1"
