name: Runner macos workflow

on:
    push:
        branches:
            - main

jobs:
    macos-runner-build-test:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout

            - name: Create Swift File
              run: |
                echo print("Hello from swift on macos") > hello.swift

            - name: Install dependencies
              run: swiftlint

            - name: Compile and run swift program
              run: |
                swiftc hello.swift
                ./hello
              