name: sheduled_event
on:
    schedule:
        - cron: '*/1 * * * *'
jobs:
    event_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Echo current time
              run: echo "The current server time is $(date)."