name: Workflow context workflows

on: ['push']

jobs:
  workflow-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: |
          echo "My action:! $MY_ACTION"
          echo "My actor:! $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}
