name: "workflow command"
on:
  push:
    branches:
      - main
jobs:
  workflow-command-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::My group Message"
          echo "Msg1"
          echo "Msg2"
          echo "::endgroup::"
      - name: "github env"
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: "output_val"
        run: |
          echo $MY_VAL
